### ISSUE TITLE
debug build of dotnet runtime 8.0.10 crashes with an assertion after merging datadog 3.3.1

### ISSUE THREAD

**Issue by korniltsev** [grafana/pyroscope-dotnet#79]
```
Assert failure(PID 194626 [0x0002f842], Thread: 194637 [0x2f84d]): TypeFromToken(pd) == mdtParamDef
    File: /home/korniltsev/github/runtime/src/coreclr/md/compiler/import.cpp Line: 2749
    Image: /home/korniltsev/p/pyroscope/examples/language-sdk-instrumentation/dotnet/rideshare/example/bin/Release/net8.0/linux-x64/publish/example
```

The issue reproduces with datadog profiler as well with this configuration

```
"ASPNETCORE_URLS=http://127.0.0.1:7000",
		"CORECLR_ENABLE_PROFILING=1",
		"CORECLR_PROFILER={BD1A650D-AC5D-4896-B64F-D6FA25D6B26A}",
		"CORECLR_PROFILER_PATH=/home/korniltsev/p/DD/dd-trace-dotnet-release-341/linux-x64/Datadog.Profiler.Native.so",
		"DD_PROFILING_ENABLED=1",
		"DD_TRACE_DEBUG=1",
		"DD_TRACE_LOG_DIRECTORY=/home/korniltsev/p/pyroscope-dotnet/build-debug/logs",
		"LD_PRELOAD=/home/korniltsev/p/DD/dd-trace-dotnet-release-341/linux-x64/Datadog.Linux.ApiWrapper.x64.so",
```

**Comment by korniltsev** [comment]
```
pwndbg> bt
#0  DBG_DebugBreak () at /home/korniltsev/github/runtime/src/coreclr/pal/src/arch/amd64/debugbreak.S:9
#1  0x00007ffff552be6f in DebugBreak () at /home/korniltsev/github/runtime/src/coreclr/pal/src/debug/debug.cpp:406
#2  0x00007ffff4fdb3fb in DbgAssertDialog (szFile=0x7ffff40512c0 <str> "/home/korniltsev/github/runtime/src/coreclr/md/compiler/import.cpp", iLine=2749, szExpr=0x7ffff4051d60 <str> "TypeFromToken(pd) == mdtParamDef") at /home/korniltsev/github/runtime/src/coreclr/utilcode/debug.cpp:461
#3  0x00007ffff51bfd46 in RegMeta::GetParamProps (this=0x612000072940, pd=0, pmd=0x0, pulSequence=0x7fff7480ca70, szName=0x7fff7480ca80 u"segment", cchName=259, pchName=0x7fff7480cd10, pdwAttr=0x7fff7480c510, pdwCPlusTypeFlag=0x7fff7480cd20, ppValue=0x0, pchValue=0x0) at /home/korniltsev/github/runtime/src/coreclr/md/compiler/import.cpp:2749
#4  0x00007fffee9b3371 in FrameStore::GetMethodSignature (this=0x614000003a40, pInfo=0x6020000035d0, pMetaData=0x612000072940, mdTokenType=33554570, functionId=140735221300952, mdTokenFunc=100664225) at /home/korniltsev/p/pyroscope-dotnet/profiler/src/ProfilerEngine/Datadog.Profiler.Native/FrameStore.cpp:1027
#5  0x00007fffee9aed83 in FrameStore::GetManagedFrame (this=0x614000003a40, functionId=140735221300952) at /home/korniltsev/p/pyroscope-dotnet/profiler/src/ProfilerEngine/Datadog.Profiler.Native/FrameStore.cpp:180
#6  0x00007fffee9ad827 in FrameStore::GetFrame (this=0x614000003a40, instructionPointer=140735180302062) at /home/korniltsev/p/pyroscope-dotnet/profiler/src/ProfilerEngine/Datadog.Profiler.Native/FrameStore.cpp:83
#7  0x00007fffee963d73 in CollectorBase<RawCpuSample>::SetStack (this=0x611000007ac0, rawSample=..., sample=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<Sample, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<Sample, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<Sample> (use count 1, weak count 0) = {...}) at /home/korniltsev/p/pyroscope-dotnet/profiler/src/ProfilerEngine/Datadog.Profiler.Native.Linux/../Datadog.Profiler.Native/CollectorBase.h:212
#8  0x00007fffee9636e5 in CollectorBase<RawCpuSample>::TransformRawSample (this=0x611000007ac0, rawSample=..., sample=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<Sample, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<Sample, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<Sample> (use count 1, weak count 0) = {...}) at /home/korniltsev/p/pyroscope-dotnet/profiler/src/ProfilerEngine/Datadog.Profiler.Native.Linux/../Datadog.Profiler.Native/CollectorBase.h:120
#9  0x00007fffee962743 in CollectorBase<RawCpuSample>::SamplesEnumeratorImpl::MoveNext (this=0x60b000c319c0, sample=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<Sample, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<Sample, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<Sample> (use count 1, weak count 0) = {...}) at /home/korniltsev/p/pyroscope-dotnet/profiler/src/ProfilerEngine/Datadog.Profiler.Native.Linux/../Datadog.Profiler.Native/CollectorBase.h:174
#10 0x00007fffeeb3a849 in SamplesCollector::CollectSamples (this=0x611000007d40, samplesProviders=std::forward_list = {...}) at /home/korniltsev/p/pyroscope-dotnet/profiler/src/ProfilerEngine/Datadog.Profiler.Native/SamplesCollector.cpp:190
#11 0x00007fffeeb3ba3d in SamplesCollector::SamplesWork (this=0x611000007d40) at /home/korniltsev/p/pyroscope-dotnet/profiler/src/ProfilerEngine/Datadog.Profiler.Native/SamplesCollector.cpp:107
#12 0x00007fffeeb3d710 in SamplesCollector::StartImpl()::$_0::operator()() const (this=0x60200001bff8) at /home/korniltsev/p/pyroscope-dotnet/profiler/src/ProfilerEngine/Datadog.Profiler.Native/SamplesCollector.cpp:66

```

Same happens when datadog 3.4.1 used
```
#0  DBG_DebugBreak () at /home/korniltsev/github/runtime/src/coreclr/pal/src/arch/amd64/debugbreak.S:9
#1  0x00007ffff552be6f in DebugBreak () at /home/korniltsev/github/runtime/src/coreclr/pal/src/debug/debug.cpp:406
#2  0x00007ffff4fdb3fb in DbgAssertDialog (szFile=0x7ffff40512c0 <str> "/home/korniltsev/github/runtime/src/coreclr/md/compiler/import.cpp", iLine=2749, szExpr=0x7ffff4051d60 <str> "TypeFromToken(pd) == mdtParamDef") at /home/korniltsev/github/runtime/src/coreclr/utilcode/debug.cpp:461
#3  0x00007ffff51bfd46 in RegMeta::GetParamProps (this=0x612000063940, pd=0, pmd=0x0, pulSequence=0x7fffec88c2a8, szName=0x7fffec88c710 u"", cchName=259, pchName=0x7fffec88c2a4, pdwAttr=0x7fffec88c24c, pdwCPlusTypeFlag=0x7fffec88c2a0, ppValue=0x0, pchValue=0x0) at /home/korniltsev/github/runtime/src/coreclr/md/compiler/import.cpp:2749
#4  0x00007fffef364623 in ?? () from /home/korniltsev/p/DD/dd-trace-dotnet-release-341/linux-x64/Datadog.Profiler.Native.so
#5  0x00007fffef362376 in ?? () from /home/korniltsev/p/DD/dd-trace-dotnet-release-341/linux-x64/Datadog.Profiler.Native.so

```
